spring:
  profiles:
    active:
      - dev
---
spring:
  config:
    activate:
      on-profile: dev
  mail:
    host: smtp.gmail.com
    username: xxxxxxxxxxxx@gmail.com
    password: xxxxxxxxxxxxx
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
server:
  error:
    include-message: always
logging:
  level:
    root: INFO
